#!/bin/sh

if which paru ; then
    echo "Paru is already installed"
else
    # Install paru AUR helper
    sudo pacman -S --needed base-devel --noconfirm
    git clone https://aur.archlinux.org/paru-bin.git ~/paru
    cd ~/paru
    makepkg -si --noconfirm && cd ~ && rm -rf ~/paru
fi

# Install dependencies
cat ~/.config/yadm/requirements.txt | xargs paru -Syyu --noconfirm

# Enable user daemons
systemctl --user enable --now emacs.service
systemctl --user enable --now trash-empty.timer

# Install oh-my-zsh
chsh -s /usr/bin/zsh
mkdir -p ~/.cache/zsh
mkdir -p ~/.local/share/oh-my-zsh
git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.local/share/oh-my-zsh
